apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: php-backend
spec:
  selector:
    app: php-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80